version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: virtual-id-backend
    ports:
    - 8000:8000
    depends_on:
    - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/virtualid
      REDIS_HOST: redis
      REDIS_PORT: '6379'
    networks:
    - virtualid-net
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: virtual-id-frontend
    ports:
    - 3000:3000
    depends_on:
    - backend
    networks:
    - virtualid-net
    environment:
      REDIS_HOST: redis
      REDIS_PORT: '6379'
  db:
    image: postgres:13
    container_name: virtual-id-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: virtualid
    volumes:
    - db_data:/var/lib/postgresql/data
    ports:
    - 5432:5432
    networks:
    - virtualid-net
  redis:
    image: redis:7
    container_name: redis
    ports:
    - 6379:6379
    volumes:
    - redis_data:/data
    restart: always
volumes:
  db_data: {}
  redis_data: null
networks:
  virtualid-net:
    driver: bridge
